name = "ledger"
defaultTargets = ["Ledger", "ledger"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "Ledger"

[[lean_exe]]
name = "ledger"
root = "Main"
